In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
china_file = "../../data/harvard_dataverse_aqi/china_stations_w_XY.txt"
china = pd.read_csv(china_file, sep='\t')
china

     StationID StationNM  CityNM       Long       Lat      note
0        1001A      万寿西宫      北京  116.36600  39.86730       NaN
1        1002A        定陵      北京  116.17000  40.28650       NaN
2        1003A        东四      北京  116.43400  39.95220       NaN
3        1004A        天坛      北京  116.43400  39.87450       NaN
4        1005A       农展馆      北京  116.47300  39.97160       NaN
5        1006A        官园      北京  116.36100  39.94250       NaN
6        1007A     海淀区万柳      北京  116.31500  39.99340       NaN
7        1008A      顺义新城      北京  116.72000  40.14380       NaN
8        1009A       怀柔镇      北京  116.64400  40.39370       NaN
9        1010A       昌平镇      北京  116.23000  40.19520       NaN
10       1011A      奥体中心      北京  116.40700  40.00310       NaN
11       1012A        古城      北京  116.22500  39.92790       NaN
12       1013A     市监测中心      天津  117.15100  39.09700       NaN
13       1014A       南口路      天津  117.19300  39.17300       NaN
14       1015A       勤俭路      天津  117.14500  39.16540       NaN
15       1016A       南京路      天津  117.18400  39.12050       NaN
16       1017A    大直沽八号路      天津  117.23700  39.10820       NaN
17       1018A       前进路      天津  117.20200  39.09270       NaN
18       1019A    北辰科技园区      天津  117.18370  39.21330       NaN
19       1020A       天山路      天津  117.26900  39.13370       NaN
20       1021A       跃进路      天津  117.30700  39.08770       NaN
21       1023A      第四大街      天津  117.70700  39.03430       NaN
22       1024A       永明路      天津  117.45700  38.83940       NaN
23       1025A       航天路      天津  117.40100  39.12400       NaN
24       1026A       汉北路      天津  117.76400  39.15870       NaN
25       1027A       团泊洼      天津  117.15700  38.91940       NaN
26       1028A      化工学校     石家庄  114.60383  37.99018  XY (Lex)
27       1029A      职工医院     石家庄  114.45480  38.05130       NaN
28       1030A       高新区     石家庄  114.60460  38.03980       NaN
29       1031A      西北水源     石家庄  114.50190  38.13980       NaN
...        ...       ...     ...        ...       ...       ...
1467     2686A      市环保局   吐鲁番地区   89.19100  42.94090       NaN
1468     2687A     地区环保局   吐鲁番地区   89.16730  42.95590       NaN
1469     2688A     地区监测站    哈密地区   93.51280  42.81720       NaN
1470     2689A    哈密师范学校    哈密地区   93.49610  42.83280       NaN
1471     2690A      天山天池     昌吉州   87.98970  44.15640       NaN
1472     2691A      州监测站     昌吉州   87.29970  44.01140       NaN
1473     2692A    新区政务中心     昌吉州   87.27170  44.02970       NaN
1474     2693A    博乐市西郊区      博州   82.04850  44.90790       NaN
1475     2694A      市环保局      博州   82.08060  44.89690       NaN
1476     2695A       电视台   阿克苏地区   80.28280  41.16360       NaN
1477     2696A      艺术中心   阿克苏地区   80.29560  41.19330       NaN
1478     2697A     市人民政府      克州   76.18610  39.71530       NaN
1479     2698A      巡警大队    喀什地区   75.98280  39.53710       NaN
1480     2699A        吾办    喀什地区   75.97710  39.46990       NaN
1481     2700A    市环境监测站    喀什地区   75.94350  39.43650       NaN
1482     2701A       地区站    和田地区   79.94850  37.11520       NaN
1483     2702A   古江巴格乡院内    和田地区   79.91170  37.10130       NaN
1484     2703A      市环保局  伊犁哈萨克州   81.28150  43.94040       NaN
1485     2704A     新政府片区  伊犁哈萨克州   81.28670  43.89500       NaN
1486     2705A      第二水厂  伊犁哈萨克州   81.33640  43.94100       NaN
1487     2706A    东门外小游园    塔城地区   82.99940  46.74320       NaN
1488     2707A       小东沟   阿勒泰地区   88.12140  47.90470       NaN
1489     2708A        市站   阿勒泰地区   88.12670  47.85150       NaN
1490     2709A     艾青诗歌馆     石河子   86.04970  44.29670       NaN
1491     2710A      阳光学校     石河子   86.06970  44.30750       NaN
1492     2711A      农水大厦     五家渠   87.54750  44.17560       NaN
1493     2835A      四十中小     攀枝花  101.72270  26.56700       NaN
1494     2842A      湖里中学      厦门  118.09360  24.50580       NaN
1495     2845A       德盛苑      长治  113.15690  36.19120       NaN
1496     2846A       体育西      广州  113.32080  23.13230       NaN

[1497 rows x 6 columns]

In [3]:
coords = china[['StationID', 'Long', 'Lat']]
coords.columns = [['id', 'long', 'lat']]
coords

         id       long       lat
0     1001A  116.36600  39.86730
1     1002A  116.17000  40.28650
2     1003A  116.43400  39.95220
3     1004A  116.43400  39.87450
4     1005A  116.47300  39.97160
5     1006A  116.36100  39.94250
6     1007A  116.31500  39.99340
7     1008A  116.72000  40.14380
8     1009A  116.64400  40.39370
9     1010A  116.23000  40.19520
10    1011A  116.40700  40.00310
11    1012A  116.22500  39.92790
12    1013A  117.15100  39.09700
13    1014A  117.19300  39.17300
14    1015A  117.14500  39.16540
15    1016A  117.18400  39.12050
16    1017A  117.23700  39.10820
17    1018A  117.20200  39.09270
18    1019A  117.18370  39.21330
19    1020A  117.26900  39.13370
20    1021A  117.30700  39.08770
21    1023A  117.70700  39.03430
22    1024A  117.45700  38.83940
23    1025A  117.40100  39.12400
24    1026A  117.76400  39.15870
25    1027A  117.15700  38.91940
26    1028A  114.60383  37.99018
27    1029A  114.45480  38.05130
28    1030A  114.60460  38.03980
29    1031A  114.50190  38.13980
...     ...        ...       ...
1467  2686A   89.19100  42.94090
1468  2687A   89.16730  42.95590
1469  2688A   93.51280  42.81720
1470  2689A   93.49610  42.83280
1471  2690A   87.98970  44.15640
1472  2691A   87.29970  44.01140
1473  2692A   87.27170  44.02970
1474  2693A   82.04850  44.90790
1475  2694A   82.08060  44.89690
1476  2695A   80.28280  41.16360
1477  2696A   80.29560  41.19330
1478  2697A   76.18610  39.71530
1479  2698A   75.98280  39.53710
1480  2699A   75.97710  39.46990
1481  2700A   75.94350  39.43650
1482  2701A   79.94850  37.11520
1483  2702A   79.91170  37.10130
1484  2703A   81.28150  43.94040
1485  2704A   81.28670  43.89500
1486  2705A   81.33640  43.94100
1487  2706A   82.99940  46.74320
1488  2707A   88.12140  47.90470
1489  2708A   88.12670  47.85150
1490  2709A   86.04970  44.29670
1491  2710A   86.06970  44.30750
1492  2711A   87.54750  44.17560
1493  2835A  101.72270  26.56700
1494  2842A  118.09360  24.50580
1495  2845A  113.15690  36.19120
1496  2846A  113.32080  23.13230

[1497 rows x 3 columns]

In [36]:
hk_file = "../../data/hongkong_taiwan_aqi/hongkong_monitor_coords.csv"
hk = pd.read_csv(hk_file, skiprows=2)

In [37]:
hk = hk[['ENGLISH NAME', 'LONGITUDE', 'LATITUDE']]
hk

                                      ENGLISH NAME  LONGITUDE  LATITUDE
0           Eastern Air Quality Monitoring Station  114-13-10  22-16-58
1          Tuen Mun Air Quality Monitoring Station  113-58-36  22-23-28
2        Tung Chung Air Quality Monitoring Station  113-56-37  22-17-20
3          Mong Kok Air Quality Monitoring Station   114-10-6  22-19-21
4           Central Air Quality Monitoring Station   114-9-29  22-16-55
5           Tap Mun Air Quality Monitoring Station  114-21-39  22-28-17
6      Causeway Bay Air Quality Monitoring Station   114-11-6  22-16-48
7     Tseung Kwan O Air Quality Monitoring Station  114-15-34   22-19-4
8      Sham Shui Po Air Quality Monitoring Station   114-9-33  22-19-49
9        Kwai Chung Air Quality Monitoring Station   114-7-47  22-21-26
10           Tai Po Air Quality Monitoring Station   114-9-52   22-27-3
11          Sha Tin Air Quality Monitoring Station   114-11-4  22-22-35
12        Yuen Long Air Quality Monitoring Station   114-1-22  22-26-43
13  Central/Western Air Quality Monitoring Station   114-8-40   22-17-6
14        Kwun Tong Air Quality Monitoring Station  114-13-29  22-18-48
15        Tsuen Wan Air Quality Monitoring Station   114-6-52  22-22-18

In [38]:
hk = hk.assign(id = [str(i) + 'HK' for i in range(16)])

In [39]:
def convert(tudes):
    return np.array([sum(float(x) / 60 ** n for n, x in enumerate(tude.split('-'))) for tude in tudes])

In [40]:
hk.loc[:,'LONGITUDE'] = convert(hk['LONGITUDE'].values)

In [42]:
hk.loc[:,'LATITUDE'] = convert(hk['LATITUDE'].values)

In [43]:
hk

,ENGLISH NAME,LONGITUDE,LATITUDE,id
0,Eastern Air Quality Monitoring Station,114.219444,22.282778,0HK
1,Tuen Mun Air Quality Monitoring Station,113.976667,22.391111,1HK
2,Tung Chung Air Quality Monitoring Station,113.943611,22.288889,2HK
3,Mong Kok Air Quality Monitoring Station,114.168333,22.322500,3HK
4,Central Air Quality Monitoring Station,114.158056,22.281944,4HK
5,Tap Mun Air Quality Monitoring Station,114.360833,22.471389,5HK
6,Causeway Bay Air Quality Monitoring Station,114.185000,22.280000,6HK
7,Tseung Kwan O Air Quality Monitoring Station,114.259444,22.317778,7HK
8,Sham Shui Po Air Quality Monitoring Station,114.159167,22.330278,8HK
9,Kwai Chung Air Quality Monitoring Station,114.129722,22.357222,9HK
10,Tai Po Air Quality Monitoring Station,114.164444,22.450833,10HK
11,Sha Tin Air Quality Monitoring Station,114.184444,22.376389,11HK
12,Yuen Long Air Quality Monitoring Station,114.022778,22.445278,12HK
13,Central/Western Air Quality Monitoring Station,114.144444,22.285000,13HK
14,Kwun Tong Air Quality Monitoring Station,114.224722,22.313333,14HK
15,Tsuen Wan Air Quality Monitoring Station,114.114444,22.371667,15HK

In [44]:
hk.to_csv("../../data/hongkong_taiwan_aqi/hongkong_monitor_coords_processed.csv")

In [47]:
hk.columns

Index(['ENGLISH NAME', 'long', 'lat', 'id'], dtype='object')

In [46]:
hk.columns = ['ENGLISH NAME', 'long', 'lat', 'id']

In [48]:
hk = hk[['id', 'long', 'lat']]

In [49]:
coords = coords.append(hk, ignore_index=True)

In [51]:
tw_file = "../../data/hongkong_taiwan_aqi/taiwan_monitor_coords.csv"
tw = pd.read_csv(tw_file)

In [53]:
tw = tw[0:76]

In [55]:
tw = tw[['測站名稱', '經度', '緯度']]
tw.columns = ['Name', 'long', 'lat']

In [57]:
tw = tw.assign(id = [str(i) + 'TW' for i in range(76)])

In [58]:
tw.to_csv("../../data/hongkong_taiwan_aqi/taiwan_monitor_coords_processed.csv")

In [59]:
tw = tw[['id', 'long', 'lat']]

In [60]:
coords = coords.append(tw, ignore_index=True)

In [61]:
coords.to_csv("../../data/processed/monitor_coords.csv", index=False)

In [66]:
coords[1470:]

         id        long        lat
1470  2689A   93.496100  42.832800
1471  2690A   87.989700  44.156400
1472  2691A   87.299700  44.011400
1473  2692A   87.271700  44.029700
1474  2693A   82.048500  44.907900
1475  2694A   82.080600  44.896900
1476  2695A   80.282800  41.163600
1477  2696A   80.295600  41.193300
1478  2697A   76.186100  39.715300
1479  2698A   75.982800  39.537100
1480  2699A   75.977100  39.469900
1481  2700A   75.943500  39.436500
1482  2701A   79.948500  37.115200
1483  2702A   79.911700  37.101300
1484  2703A   81.281500  43.940400
1485  2704A   81.286700  43.895000
1486  2705A   81.336400  43.941000
1487  2706A   82.999400  46.743200
1488  2707A   88.121400  47.904700
1489  2708A   88.126700  47.851500
1490  2709A   86.049700  44.296700
1491  2710A   86.069700  44.307500
1492  2711A   87.547500  44.175600
1493  2835A  101.722700  26.567000
1494  2842A  118.093600  24.505800
1495  2845A  113.156900  36.191200
1496  2846A  113.320800  23.132300
1497    0HK  114.219444  22.282778
1498    1HK  113.976667  22.391111
1499    2HK  113.943611  22.288889
...     ...         ...        ...
1559   46TW  121.082761  25.035503
1560   47TW  121.216350  24.863869
1561   48TW  121.221667  24.953278
1562   49TW  121.203986  24.952786
1563   50TW  121.088903  24.740644
1564   51TW  121.038653  24.900142
1565   52TW  120.758833  24.382942
1566   53TW  120.820200  24.565269
1567   54TW  120.898572  24.696969
1568   55TW  120.469061  24.131672
1569   56TW  120.541519  24.066000
1570   57TW  120.409653  23.925175
1571   58TW  120.967903  23.968842
1572   59TW  120.685306  23.913000
1573   60TW  120.677306  23.756389
1574   61TW  120.251825  23.753506
1575   62TW  120.202842  23.717533
1576   63TW  120.348742  23.757547
1577   64TW  120.544994  23.711853
1578   65TW  120.345531  23.554839
1579   66TW  120.247350  23.465308
1580   67TW  120.788928  21.958069
1581   68TW  120.488033  22.673081
1582   69TW  120.561175  22.523108
1583   70TW  121.150450  22.755358
1584   71TW  121.161933  23.045083
1585   72TW  121.599769  23.971306
1586   73TW  119.566158  23.569031
1587   74TW  118.312256  24.432133
1588   75TW  119.949875  26.160469

[119 rows x 3 columns]